services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'
            PoP\ComponentModel\Schema\FeedbackMessageStoreInterface: '@feedback_message_store'
            PoP\QueryParsing\QueryParserInterface: '@query_parser'

    site_object:
        class: \PoP\Multisite\ObjectModels\Site
        public: true

    PoP\Multisite\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Multisite\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true
